<a href="https://colab.research.google.com/github/Aefano23/Numpy_Practice_Project/blob/main/Aditya_Efano_Putra_Numpy_Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Mini Project Numpy**

**1. Extract all odd numbers from arr**

In [ ]:
#Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Code Here
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = arr[arr % 2 != 0]
print(odd)

[1 3 5 7 9]


Output Seharusnya:
>array([1, 3, 5, 7, 9])

**2. Convert a 1D array to a 2D array with 2 rows**

In [ ]:
#Input
np.arange(10)

In [ ]:
#Code Here

print(np.arange(10).reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


Output Seharusnya:
>array([[0, 1, 2, 3, 4],
 ><br>     [5, 6, 7, 8, 9]])





**3. Stack arrays a and b vertically**

In [ ]:
#Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
#Code Here
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.stack((a,b)))

[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


Output Seharusnya:
> array([[0, 1, 2, 3, 4],
>  <br>      [5, 6, 7, 8, 9],
>  <br>      [1, 1, 1, 1, 1],
>    <br>    [1, 1, 1, 1, 1]])

**4. Swap columns 1 and 2 in the array arr.**

In [ ]:
#Input
arr = np.arange(9).reshape(3,3)
arr

In [ ]:
#Code here
arr = np.arange(9).reshape(3,3)
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


Output Seharusnya:
> array([[1, 0, 2],
>     <br>   [4, 3, 5],
>     <br>   [7, 6, 8]])

**5. Replace all odd numbers in arr with -1**

In [ ]:
#Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Output Seharusnya:
> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6. Convert a 1-D array to a 3-D array**

In [ ]:
#Input
a = np.array([x for x in range(27)])

In [ ]:
#Code Here
a = np.array([x for x in range(27)])
print(a.reshape(3,3,3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Output Seharusnya:
>[[[ 0  1  2]
> <br>  [ 3  4  5]
> <br> [ 6  7  8]]
<br>
> <br> [[ 9 10 11]
> <br>  [12 13 14]
> <br> [15 16 17]]
<br>
> <br> [[18 19 20]
> <br> [21 22 23]
> <br> [24 25 26]]]

**7. Output the transpose of a matrix (as numpy array)**

In [ ]:
#Input
a = np.array([[11,32,53],
              [64,25,16],
              [47,28,39]])

In [ ]:
#Code here
a = np.array([[11,32,53],
              [64,25,16],
              [47,28,39]])
new = a - np.floor_divide(a,10)*10 #per nilai dilakukan pembagian kebawah dengan 10, kemudian hasilnya dikali 10 (ini disebut pengurang). nilai awal kemudian dikurang dengan pengurang sehingga diperolehlah digit satuan dari setiap elemen
new_transpose =  new.transpose()
print(new_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


output Seharusnya:
> [[1 4 7]
> <br> [2 5 8]
> <br> [3 6 9]]

**8. How to get the desired result from both of these arrays**

In [ ]:
#Input
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [ ]:
#Code here
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])
print(np.add(a,b))

[[11 13 15]
 [17 19 21]]


Output Seharusnya:
>[[11 13 15]
> <br> [17 19 21]]

**9. Selesaikan soal dibawah ini**

In [ ]:
# Berikan 2 ke variable apple_price
apple_price = 2

# Berikan 5 ke variable count
count = 5

# Berikan hasil dari apple_price * count ke variable total_price
total_price = apple_price * count

# Dengan menggunakan variable count, cetak 'Anda akan membeli .. apel'
#CODE HERE
print(f"Anda akan membeli {count} apel")

# Dengan menggunakan variable total_price, cetak 'Harga total adalah .. dolar'
#CODE HERE
print(f"Harga total adalah {total_price} dolar")

Anda akan membeli 5 apel
Harga total adalah 10 dolar


**10. Selesaikan Soal dibawah ini**

In [ ]:
items = {"nama_barang":"apel","deskripsi":[{
    "harga":20,
    "foto":"assets/images/apple.jpg",
    "qty":100
}], "nama_barang":"jeruk","deskripsi":[{
    "harga":25,
    "foto":"assets/images/jeruk.jpg",
    "qty":150
}] }

In [ ]:
# Berikan 20 ke variable money
money = 20

items = {'apel': 2, 'pisang': 4, 'jeruk': 6}
for item_name in items:
    print('--------------------------------------------------')
    # Menggunakan variable money, cetak 'Anda memiliki ___ dolar di dompet Anda'
    #CODE HERE
    print(f"Anda memiliki {money} dolar di dompet Anda")
    #CODE BELOW
    print('Harga setiap '+ item_name +' '+ str(items[item_name]) + ' dolar')

    input_count = input('Mau berapa ' + item_name + '?:')
    print('Anda akan membeli' , input_count , item_name)

    count = int(input_count)
    total_price = items[item_name] * count
    print('Harga total adalah ' + str(total_price) + ' dolar')

    # Tambahkan control flow berdasarkan perbandingan dari money dan total_price
    if(money >= total_price):
      print("Anda telah membeli "+ item_name + ' ' + str(items[item_name]))
      money = money - total_price
    else:
      print("Uang Anda tidak mencukupi")
      print("Anda tidak dapat membeli "+ item_name +" sebanyak itu")
